// Comprehensive seed data generator for all 28 Indian states
// Each state: 5 cities, each city: 10 places, 5 hotels, 5 restaurants

const IMAGE_URLS = [
  'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800',
  'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=800',
  'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800',
  'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800',
  'https://images.unsplash.com/photo-1568632434978-8e8ca8c3f1ba?w=800',
  'https://images.unsplash.com/photo-1586041828039-b8d193d6d1a9?w=800',
  'https://images.unsplash.com/photo-1589831377283-33cb1cc6bd5e?w=800',
  'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800',
  'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800',
  'https://images.unsplash.com/photo-1609340655213-cce5f8dc1ddb?w=800',
  'https://images.unsplash.com/photo-1570655652364-2632e47aff2f?w=800',
  'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
  'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
  'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800',
  'https://images.unsplash.com/photo-1585016495481-91a2e71f2a4c?w=800',
  'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800',
  'https://images.unsplash.com/photo-1602652428009-6c96e1a9b9c7?w=800',
  'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800',
  'https://images.unsplash.com/photo-1536421469767-80559bb6f5e1?w=800',
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
  'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800',
  'https://images.unsplash.com/photo-1548013146-72479768bada?w=800',
  'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
  'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800',
  'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=800',
  'https://images.unsplash.com/photo-1590579491624-f98f36d4c763?w=800',
  'https://images.unsplash.com/photo-1558431460-98e7b2e29894?w=800',
  'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800',
];

const HOTEL_IMAGES = [
  'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
  'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
  'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
  'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
  'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
];

const RESTAURANT_IMAGES = [
  'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
  'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800',
  'https://images.unsplash.com/photo-1559339352-11d035aa65f4?w=800',
  'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800',
  'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
];

const AMENITIES = ['Free WiFi', 'Parking', 'Breakfast', 'Swimming Pool', 'Gym', 'Spa', 'Restaurant', 'Room Service', 'Laundry', 'Airport Shuttle'];
const CUISINES = ['Indian', 'Mughlai', 'Chinese', 'Tibetan', 'South Indian', 'Goan', 'Seafood', 'Continental', 'North Indian', 'Rajasthani', 'Kerala', 'Bengali', 'Punjabi', 'Gujarati', 'Maharashtrian'];
const CATEGORIES = ['Hill Station', 'Beach', 'Heritage', 'Wildlife', 'Religious', 'Adventure', 'Honeymoon', 'Family Trip'];

const STATES_DATA = [
  {
    name: 'Rajasthan',
    slug: 'rajasthan',
    capital: 'Jaipur',
    description: 'The Land of Kings — a mesmerising tapestry of majestic forts, gilded palaces, vast Thar Desert dunes, and vibrant folk culture.',
    image: IMAGE_URLS[0],
    gallery: IMAGE_URLS.slice(1, 4),
    weather: { summer: '38–45°C (March–June)', winter: '8–25°C (November–February)', monsoon: 'Moderate (July–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Rajasthani, Hindi',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Rajasthan Tourism', metaDescription: 'Explore Rajasthan forts, palaces and desert', keywords: ['Rajasthan', 'Jaipur', 'Jodhpur', 'desert'] },
    cities: [
      { name: 'Jaipur', slug: 'jaipur', lat: 26.9124, lng: 75.7873 },
      { name: 'Jodhpur', slug: 'jodhpur', lat: 26.2389, lng: 73.0243 },
      { name: 'Udaipur', slug: 'udaipur', lat: 24.5854, lng: 73.7125 },
      { name: 'Jaisalmer', slug: 'jaisalmer', lat: 26.9157, lng: 70.9083 },
      { name: 'Pushkar', slug: 'pushkar', lat: 26.4897, lng: 74.5511 },
    ],
  },
  {
    name: 'Kerala',
    slug: 'kerala',
    capital: 'Thiruvananthapuram',
    description: "God's Own Country — blessed with serene backwaters, lush tea plantations, pristine beaches, and rich Ayurveda traditions.",
    image: IMAGE_URLS[8],
    gallery: IMAGE_URLS.slice(9, 12),
    weather: { summer: '28–35°C (March–May)', winter: '18–28°C (November–February)', monsoon: 'Heavy (June–August)' },
    bestTimeToVisit: 'September to March',
    localLanguage: 'Malayalam',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Kerala Tourism', metaDescription: 'Discover Kerala backwaters, beaches and hills', keywords: ['Kerala', 'backwaters', 'Munnar', 'Kochi'] },
    cities: [
      { name: 'Kochi', slug: 'kochi', lat: 9.9312, lng: 76.2673 },
      { name: 'Munnar', slug: 'munnar', lat: 10.0889, lng: 77.0595 },
      { name: 'Alleppey', slug: 'alleppey', lat: 9.4981, lng: 76.3388 },
      { name: 'Kovalam', slug: 'kovalam', lat: 8.4004, lng: 76.9774 },
      { name: 'Wayanad', slug: 'wayanad', lat: 11.6854, lng: 76.1320 },
    ],
  },
  {
    name: 'Goa',
    slug: 'goa',
    capital: 'Panaji',
    description: "India's smallest state and most famous beach destination — Portuguese heritage meets sun-soaked shores and vibrant nightlife.",
    image: IMAGE_URLS[23],
    gallery: IMAGE_URLS.slice(24, 27),
    weather: { summer: '30–35°C (March–May)', winter: '20–32°C (November–February)', monsoon: 'Heavy (June–September)' },
    bestTimeToVisit: 'November to February',
    localLanguage: 'Konkani, English',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Goa Tourism', metaDescription: 'Plan your Goa trip — beaches, heritage and nightlife', keywords: ['Goa', 'beaches', 'Baga', 'nightlife'] },
    cities: [
      { name: 'Panaji', slug: 'panaji', lat: 15.4989, lng: 73.8278 },
      { name: 'Margao', slug: 'margao', lat: 15.2700, lng: 73.9500 },
      { name: 'Mapusa', slug: 'mapusa', lat: 15.5900, lng: 73.8100 },
      { name: 'Ponda', slug: 'ponda', lat: 15.4000, lng: 74.0000 },
      { name: 'Vasco', slug: 'vasco', lat: 15.3950, lng: 73.8200 },
    ],
  },
  {
    name: 'West Bengal',
    slug: 'west-bengal',
    capital: 'Kolkata',
    description: 'The cultural heart of India — home to Kolkata, misty Darjeeling hills, magical Sundarbans and artistic legacy of Tagore.',
    image: IMAGE_URLS[19],
    gallery: IMAGE_URLS.slice(17, 20),
    weather: { summer: '32–42°C (March–June)', winter: '10–22°C (November–February)', monsoon: 'Heavy (June–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Bengali, Hindi, English',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'West Bengal Tourism', metaDescription: 'Explore Kolkata, Darjeeling and Sundarbans', keywords: ['West Bengal', 'Kolkata', 'Darjeeling', 'Sundarbans'] },
    cities: [
      { name: 'Kolkata', slug: 'kolkata', lat: 22.5726, lng: 88.3639 },
      { name: 'Darjeeling', slug: 'darjeeling', lat: 27.0410, lng: 88.2663 },
      { name: 'Siliguri', slug: 'siliguri', lat: 26.7271, lng: 88.3953 },
      { name: 'Durgapur', slug: 'durgapur', lat: 23.5204, lng: 87.3119 },
      { name: 'Asansol', slug: 'asansol', lat: 23.6739, lng: 86.9524 },
    ],
  },
  {
    name: 'Uttar Pradesh',
    slug: 'uttar-pradesh',
    capital: 'Lucknow',
    description: 'The spiritual and historical soul of India — home to the Taj Mahal, holy Varanasi ghats, and Buddhist heritage of Sarnath.',
    image: IMAGE_URLS[21],
    gallery: IMAGE_URLS.slice(20, 23),
    weather: { summer: '38–46°C (April–June)', winter: '5–22°C (December–February)', monsoon: 'Warm (July–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Hindi, Urdu',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Uttar Pradesh Tourism', metaDescription: 'Visit Taj Mahal, Varanasi and Mathura', keywords: ['UP', 'Taj Mahal', 'Varanasi', 'Agra'] },
    cities: [
      { name: 'Agra', slug: 'agra', lat: 27.1767, lng: 78.0081 },
      { name: 'Varanasi', slug: 'varanasi', lat: 25.3176, lng: 82.9739 },
      { name: 'Lucknow', slug: 'lucknow', lat: 26.8467, lng: 80.9462 },
      { name: 'Mathura', slug: 'mathura', lat: 27.4924, lng: 77.6737 },
      { name: 'Prayagraj', slug: 'prayagraj', lat: 25.4358, lng: 81.8463 },
    ],
  },
  {
    name: 'Himachal Pradesh',
    slug: 'himachal-pradesh',
    capital: 'Shimla',
    description: 'The land of snow-capped peaks and apple orchards — colonial hill stations, adventure destinations and serene valleys.',
    image: IMAGE_URLS[13],
    gallery: IMAGE_URLS.slice(12, 15),
    weather: { summer: '15–28°C (April–June)', winter: '-5 to 15°C (December–February)', monsoon: 'Heavy (July–September)' },
    bestTimeToVisit: 'March to June, September to November',
    localLanguage: 'Hindi, Pahadi',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Himachal Pradesh Tourism', metaDescription: 'Explore Shimla, Manali and Spiti Valley', keywords: ['Himachal', 'Shimla', 'Manali', 'Spiti'] },
    cities: [
      { name: 'Shimla', slug: 'shimla', lat: 31.1048, lng: 77.1734 },
      { name: 'Manali', slug: 'manali', lat: 32.2432, lng: 77.1892 },
      { name: 'Dharamshala', slug: 'dharamshala', lat: 32.2190, lng: 76.3234 },
      { name: 'Kullu', slug: 'kullu', lat: 31.9582, lng: 77.1085 },
      { name: 'Kasol', slug: 'kasol', lat: 31.9900, lng: 77.3200 },
    ],
  },
  {
    name: 'Jammu and Kashmir',
    slug: 'jammu-and-kashmir',
    capital: 'Srinagar',
    description: 'Paradise on Earth — Dal Lake houseboats, Gulmarg ski slopes, floating gardens and serene monasteries of Ladakh.',
    image: IMAGE_URLS[16],
    gallery: IMAGE_URLS.slice(15, 18),
    weather: { summer: '15–30°C (May–August)', winter: '-8 to 5°C (December–February)', monsoon: 'Mild (July–August)' },
    bestTimeToVisit: 'April to October',
    localLanguage: 'Kashmiri, Urdu, Dogri',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Jammu & Kashmir Tourism', metaDescription: 'Discover Dal Lake, Gulmarg and Pahalgam', keywords: ['Kashmir', 'Dal Lake', 'Gulmarg', 'Srinagar'] },
    cities: [
      { name: 'Srinagar', slug: 'srinagar', lat: 34.0837, lng: 74.7973 },
      { name: 'Gulmarg', slug: 'gulmarg', lat: 34.0480, lng: 74.3800 },
      { name: 'Pahalgam', slug: 'pahalgam', lat: 34.0150, lng: 75.3200 },
      { name: 'Leh', slug: 'leh', lat: 34.1526, lng: 77.5771 },
      { name: 'Jammu', slug: 'jammu', lat: 32.7266, lng: 74.8570 },
    ],
  },
  {
    name: 'Karnataka',
    slug: 'karnataka',
    capital: 'Bangalore',
    description: 'A state of extraordinary diversity — from cosmopolitan Bangalore to ancient Hampi ruins, royal Mysuru and coffee-scented Coorg.',
    image: IMAGE_URLS[5],
    gallery: IMAGE_URLS.slice(4, 7),
    weather: { summer: '28–36°C (March–May)', winter: '15–28°C (November–February)', monsoon: 'Heavy (June–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Kannada',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Karnataka Tourism', metaDescription: 'Explore Hampi, Mysuru and Coorg', keywords: ['Karnataka', 'Hampi', 'Mysuru', 'Coorg'] },
    cities: [
      { name: 'Bangalore', slug: 'bangalore', lat: 12.9716, lng: 77.5946 },
      { name: 'Mysuru', slug: 'mysuru', lat: 12.2958, lng: 76.6394 },
      { name: 'Hampi', slug: 'hampi', lat: 15.3350, lng: 76.4600 },
      { name: 'Coorg', slug: 'coorg', lat: 12.4244, lng: 75.7382 },
      { name: 'Gokarna', slug: 'gokarna', lat: 14.5500, lng: 74.3167 },
    ],
  },
  {
    name: 'Tamil Nadu',
    slug: 'tamil-nadu',
    capital: 'Chennai',
    description: 'The land of Dravidian temples and classical arts — towering gopurams, pristine beaches, Ooty hills and ancient traditions.',
    image: IMAGE_URLS[27],
    gallery: IMAGE_URLS.slice(26, 28),
    weather: { summer: '32–40°C (March–June)', winter: '22–32°C (November–February)', monsoon: 'Oct–Dec (NE), Jun–Sep (SW)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Tamil',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Tamil Nadu Tourism', metaDescription: 'Discover Madurai, Ooty and Mahabalipuram', keywords: ['Tamil Nadu', 'Madurai', 'Ooty', 'Mahabalipuram'] },
    cities: [
      { name: 'Chennai', slug: 'chennai', lat: 13.0827, lng: 80.2707 },
      { name: 'Madurai', slug: 'madurai', lat: 9.9252, lng: 78.1198 },
      { name: 'Ooty', slug: 'ooty', lat: 11.4102, lng: 76.6950 },
      { name: 'Mahabalipuram', slug: 'mahabalipuram', lat: 12.6269, lng: 80.1927 },
      { name: 'Kodaikanal', slug: 'kodaikanal', lat: 10.2381, lng: 77.4892 },
    ],
  },
  {
    name: 'Maharashtra',
    slug: 'maharashtra',
    capital: 'Mumbai',
    description: "India's financial capital and much more — from bustling Mumbai to ancient Ajanta-Ellora caves and cool Mahabaleshwar valleys.",
    image: IMAGE_URLS[20],
    gallery: IMAGE_URLS.slice(19, 22),
    weather: { summer: '28–38°C (March–June)', winter: '15–30°C (November–February)', monsoon: 'Heavy (June–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Marathi, Hindi',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Maharashtra Tourism', metaDescription: 'Explore Mumbai, Ajanta-Ellora and Lonavala', keywords: ['Maharashtra', 'Mumbai', 'Ajanta', 'Ellora'] },
    cities: [
      { name: 'Mumbai', slug: 'mumbai', lat: 19.0760, lng: 72.8777 },
      { name: 'Pune', slug: 'pune', lat: 18.5204, lng: 73.8567 },
      { name: 'Nashik', slug: 'nashik', lat: 19.9975, lng: 73.7898 },
      { name: 'Aurangabad', slug: 'aurangabad', lat: 19.8762, lng: 75.3433 },
      { name: 'Lonavala', slug: 'lonavala', lat: 18.7540, lng: 73.4060 },
    ],
  },
  {
    name: 'Gujarat',
    slug: 'gujarat',
    capital: 'Gandhinagar',
    description: 'The land of Gandhi and vibrant traditions — white salt desert of Rann of Kutch, Gir lions and colourful folk culture.',
    image: IMAGE_URLS[27],
    gallery: IMAGE_URLS.slice(26, 28),
    weather: { summer: '35–45°C (April–June)', winter: '12–28°C (November–February)', monsoon: 'Moderate (July–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Gujarati, Hindi',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Gujarat Tourism', metaDescription: 'Visit Rann of Kutch, Gir Forest and Somnath', keywords: ['Gujarat', 'Rann of Kutch', 'Gir', 'Somnath'] },
    cities: [
      { name: 'Ahmedabad', slug: 'ahmedabad', lat: 23.0225, lng: 72.5714 },
      { name: 'Surat', slug: 'surat', lat: 21.1702, lng: 72.8311 },
      { name: 'Vadodara', slug: 'vadodara', lat: 22.3072, lng: 73.1812 },
      { name: 'Diu', slug: 'diu', lat: 20.7143, lng: 70.9870 },
      { name: 'Kutch', slug: 'kutch', lat: 23.2420, lng: 69.6669 },
    ],
  },
  {
    name: 'Uttarakhand',
    slug: 'uttarakhand',
    capital: 'Dehradun',
    description: 'Dev Bhoomi — the Land of Gods. Char Dham pilgrimage, yoga capital Rishikesh, Jim Corbett and Valley of Flowers.',
    image: IMAGE_URLS[14],
    gallery: IMAGE_URLS.slice(13, 16),
    weather: { summer: '15–30°C (March–June)', winter: '-5 to 15°C (December–February)', monsoon: 'Heavy (July–September)' },
    bestTimeToVisit: 'March to June, September to November',
    localLanguage: 'Hindi, Garhwali, Kumaoni',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Uttarakhand Tourism', metaDescription: 'Explore Rishikesh, Haridwar and Char Dham', keywords: ['Uttarakhand', 'Rishikesh', 'Haridwar', 'Char Dham'] },
    cities: [
      { name: 'Rishikesh', slug: 'rishikesh', lat: 30.0869, lng: 78.2676 },
      { name: 'Haridwar', slug: 'haridwar', lat: 29.9457, lng: 78.1642 },
      { name: 'Nainital', slug: 'nainital', lat: 29.3803, lng: 79.4636 },
      { name: 'Mussoorie', slug: 'mussoorie', lat: 30.4598, lng: 78.0644 },
      { name: 'Dehradun', slug: 'dehradun', lat: 30.3165, lng: 78.0322 },
    ],
  },
  {
    name: 'Andaman and Nicobar Islands',
    slug: 'andaman-and-nicobar-islands',
    capital: 'Port Blair',
    description: 'An archipelago of 572 islands — pristine white-sand beaches, crystal-clear waters, coral reefs and Cellular Jail history.',
    image: IMAGE_URLS[11],
    gallery: IMAGE_URLS.slice(10, 13),
    weather: { summer: '25–32°C (March–May)', winter: '22–30°C (November–February)', monsoon: 'Rough seas (May–October)' },
    bestTimeToVisit: 'November to April',
    localLanguage: 'Hindi, Bengali, Tamil',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Andaman Tourism', metaDescription: 'Discover Radhanagar Beach and Havelock Island', keywords: ['Andaman', 'Havelock', 'Radhanagar', 'diving'] },
    cities: [
      { name: 'Port Blair', slug: 'port-blair', lat: 11.6234, lng: 92.7265 },
      { name: 'Havelock', slug: 'havelock', lat: 12.0167, lng: 92.9667 },
      { name: 'Neil Island', slug: 'neil-island', lat: 11.8500, lng: 93.0500 },
      { name: 'Long Island', slug: 'long-island', lat: 12.3500, lng: 92.9500 },
      { name: 'Baratang', slug: 'baratang', lat: 12.1500, lng: 92.7500 },
    ],
  },
  {
    name: 'Sikkim',
    slug: 'sikkim',
    capital: 'Gangtok',
    description: "India's smallest yet most spectacular state — snow-capped Kangchenjunga, Buddhist monasteries and pristine mountain lakes.",
    image: IMAGE_URLS[13],
    gallery: IMAGE_URLS.slice(12, 15),
    weather: { summer: '15–25°C (March–June)', winter: '-5 to 12°C (December–February)', monsoon: 'Heavy (July–September)' },
    bestTimeToVisit: 'March to May, September to December',
    localLanguage: 'Nepali, Sikkimese, Lepcha',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Sikkim Tourism', metaDescription: 'Visit Gangtok, Rumtek Monastery and Tsomgo Lake', keywords: ['Sikkim', 'Gangtok', 'Rumtek', 'Kangchenjunga'] },
    cities: [
      { name: 'Gangtok', slug: 'gangtok', lat: 27.3389, lng: 88.6065 },
      { name: 'Pelling', slug: 'pelling', lat: 27.2940, lng: 88.2580 },
      { name: 'Namchi', slug: 'namchi', lat: 27.1800, lng: 88.3600 },
      { name: 'Lachung', slug: 'lachung', lat: 27.6800, lng: 88.7500 },
      { name: 'Yuksom', slug: 'yuksom', lat: 27.4500, lng: 88.2500 },
    ],
  },
  {
    name: 'Meghalaya',
    slug: 'meghalaya',
    capital: 'Shillong',
    description: 'The Abode of Clouds — living root bridges, wettest place on Earth, cascading waterfalls and charming hill town of Shillong.',
    image: IMAGE_URLS[12],
    gallery: IMAGE_URLS.slice(11, 14),
    weather: { summer: '15–25°C (April–September)', winter: '5–18°C (November–February)', monsoon: 'Extremely heavy (June–September)' },
    bestTimeToVisit: 'October to June',
    localLanguage: 'Khasi, Garo, English',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Meghalaya Tourism', metaDescription: 'Explore Cherrapunji, living root bridges and Dawki', keywords: ['Meghalaya', 'Shillong', 'Cherrapunji', 'root bridges'] },
    cities: [
      { name: 'Shillong', slug: 'shillong', lat: 25.5788, lng: 91.8933 },
      { name: 'Cherrapunji', slug: 'cherrapunji', lat: 25.2800, lng: 91.7200 },
      { name: 'Tura', slug: 'tura', lat: 25.5100, lng: 90.2100 },
      { name: 'Jowai', slug: 'jowai', lat: 25.4500, lng: 92.2000 },
      { name: 'Dawki', slug: 'dawki', lat: 25.2200, lng: 91.9200 },
    ],
  },
  {
    name: 'Odisha',
    slug: 'odisha',
    capital: 'Bhubaneswar',
    description: 'The soul of ancient India — grand Jagannath Temple, erotic sculptures of Konark, pristine beaches and rich Odissi dance.',
    image: IMAGE_URLS[27],
    gallery: IMAGE_URLS.slice(26, 28),
    weather: { summer: '30–40°C (March–June)', winter: '12–26°C (November–February)', monsoon: 'Heavy (July–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Odia',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Odisha Tourism', metaDescription: 'Visit Jagannath Temple, Konark and Chilika Lake', keywords: ['Odisha', 'Puri', 'Konark', 'Chilika'] },
    cities: [
      { name: 'Bhubaneswar', slug: 'bhubaneswar', lat: 20.2961, lng: 85.8245 },
      { name: 'Puri', slug: 'puri', lat: 19.8135, lng: 85.8312 },
      { name: 'Konark', slug: 'konark', lat: 19.8876, lng: 86.0945 },
      { name: 'Cuttack', slug: 'cuttack', lat: 20.4625, lng: 85.8830 },
      { name: 'Rourkela', slug: 'rourkela', lat: 22.2604, lng: 84.8536 },
    ],
  },
  {
    name: 'Madhya Pradesh',
    slug: 'madhya-pradesh',
    capital: 'Bhopal',
    description: 'The Heart of India — UNESCO Khajuraho temples, Bengal tigers of Kanha, historic Gwalior Fort and Buddhist stupas of Sanchi.',
    image: IMAGE_URLS[1],
    gallery: IMAGE_URLS.slice(0, 3),
    weather: { summer: '35–45°C (April–June)', winter: '8–26°C (November–February)', monsoon: 'Moderate (July–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Hindi',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Madhya Pradesh Tourism', metaDescription: 'Explore Khajuraho, Kanha and Bandhavgarh', keywords: ['MP', 'Khajuraho', 'Kanha', 'Bandhavgarh'] },
    cities: [
      { name: 'Bhopal', slug: 'bhopal', lat: 23.2599, lng: 77.4126 },
      { name: 'Indore', slug: 'indore', lat: 22.7196, lng: 75.8577 },
      { name: 'Khajuraho', slug: 'khajuraho', lat: 24.8500, lng: 79.9333 },
      { name: 'Gwalior', slug: 'gwalior', lat: 26.2183, lng: 78.1828 },
      { name: 'Jabalpur', slug: 'jabalpur', lat: 23.1815, lng: 79.9864 },
    ],
  },
  {
    name: 'Andhra Pradesh',
    slug: 'andhra-pradesh',
    capital: 'Amaravati',
    description: 'The rice bowl of India — famous Tirupati Balaji temple, classical Kuchipudi dance, Vizag beaches and Araku Valley coffee hills.',
    image: IMAGE_URLS[9],
    gallery: IMAGE_URLS.slice(8, 11),
    weather: { summer: '32–42°C (March–June)', winter: '18–30°C (November–February)', monsoon: 'Heavy (June–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Telugu',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Andhra Pradesh Tourism', metaDescription: 'Discover Tirupati, Vizag and Araku Valley', keywords: ['AP', 'Tirupati', 'Vizag', 'Araku'] },
    cities: [
      { name: 'Visakhapatnam', slug: 'visakhapatnam', lat: 17.6868, lng: 83.2185 },
      { name: 'Tirupati', slug: 'tirupati', lat: 13.6288, lng: 79.4192 },
      { name: 'Vijayawada', slug: 'vijayawada', lat: 16.5062, lng: 80.6480 },
      { name: 'Araku Valley', slug: 'araku-valley', lat: 18.3300, lng: 82.8500 },
      { name: 'Amaravati', slug: 'amaravati', lat: 16.5500, lng: 80.5200 },
    ],
  },
  {
    name: 'Assam',
    slug: 'assam',
    capital: 'Dispur',
    description: 'Gateway to Northeast India — one-horned rhinoceros of Kaziranga, Majuli river island, Brahmaputra cruises and famous Assam tea.',
    image: IMAGE_URLS[9],
    gallery: IMAGE_URLS.slice(8, 11),
    weather: { summer: '28–38°C (March–May)', winter: '8–22°C (November–February)', monsoon: 'Very heavy (June–September)' },
    bestTimeToVisit: 'November to April',
    localLanguage: 'Assamese, Bengali',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Assam Tourism', metaDescription: 'Explore Kaziranga, Majuli and tea estates', keywords: ['Assam', 'Kaziranga', 'Majuli', 'tea'] },
    cities: [
      { name: 'Guwahati', slug: 'guwahati', lat: 26.1445, lng: 91.7362 },
      { name: 'Kaziranga', slug: 'kaziranga', lat: 26.5775, lng: 93.1711 },
      { name: 'Majuli', slug: 'majuli', lat: 27.0500, lng: 94.2500 },
      { name: 'Tezpur', slug: 'tezpur', lat: 26.6333, lng: 92.8000 },
      { name: 'Dibrugarh', slug: 'dibrugarh', lat: 27.4728, lng: 94.9120 },
    ],
  },
  {
    name: 'Punjab',
    slug: 'punjab',
    capital: 'Chandigarh',
    description: 'The land of five rivers — Golden Temple at Amritsar, Wagah Border ceremony and hearty Punjabi cuisine.',
    image: IMAGE_URLS[19],
    gallery: IMAGE_URLS.slice(18, 21),
    weather: { summer: '35–45°C (April–June)', winter: '2–18°C (December–February)', monsoon: 'Moderate (July–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Punjabi, Hindi',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Punjab Tourism', metaDescription: 'Visit Golden Temple, Wagah Border and Amritsar', keywords: ['Punjab', 'Golden Temple', 'Amritsar', 'Wagah'] },
    cities: [
      { name: 'Amritsar', slug: 'amritsar', lat: 31.6340, lng: 74.8723 },
      { name: 'Chandigarh', slug: 'chandigarh', lat: 30.7333, lng: 76.7794 },
      { name: 'Ludhiana', slug: 'ludhiana', lat: 30.9010, lng: 75.8573 },
      { name: 'Patiala', slug: 'patiala', lat: 30.3398, lng: 76.3869 },
      { name: 'Jalandhar', slug: 'jalandhar', lat: 31.3260, lng: 75.5762 },
    ],
  },
  {
    name: 'Bihar',
    slug: 'bihar',
    capital: 'Patna',
    description: 'The cradle of civilisations — where Buddha attained enlightenment at Bodh Gaya, Maurya empire rose and Nalanda University educated the world.',
    image: IMAGE_URLS[21],
    gallery: IMAGE_URLS.slice(20, 23),
    weather: { summer: '38–44°C (April–June)', winter: '8–22°C (November–February)', monsoon: 'Heavy (July–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Hindi, Maithili, Bhojpuri',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Bihar Tourism', metaDescription: 'Explore Bodh Gaya, Nalanda and Rajgir', keywords: ['Bihar', 'Bodh Gaya', 'Nalanda', 'Rajgir'] },
    cities: [
      { name: 'Patna', slug: 'patna', lat: 25.5941, lng: 85.1376 },
      { name: 'Bodh Gaya', slug: 'bodh-gaya', lat: 24.6950, lng: 84.9914 },
      { name: 'Nalanda', slug: 'nalanda', lat: 25.1400, lng: 85.4400 },
      { name: 'Rajgir', slug: 'rajgir', lat: 25.0300, lng: 85.4200 },
      { name: 'Vaishali', slug: 'vaishali', lat: 25.9900, lng: 85.1400 },
    ],
  },
  {
    name: 'Arunachal Pradesh',
    slug: 'arunachal-pradesh',
    capital: 'Itanagar',
    description: "The Land of the Rising Sun — Himalayan peaks, Buddhist monasteries, tribal cultures, Sela Pass and Tawang monastery.",
    image: IMAGE_URLS[12],
    gallery: IMAGE_URLS.slice(11, 14),
    weather: { summer: '15–25°C (April–June)', winter: '-5 to 15°C (December–February)', monsoon: 'Very heavy (June–September)' },
    bestTimeToVisit: 'March to October',
    localLanguage: 'Nyishi, Adi, Hindi',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Arunachal Pradesh Tourism', metaDescription: 'Discover Tawang, Sela Pass and Ziro Valley', keywords: ['Arunachal', 'Tawang', 'Sela Pass', 'Ziro'] },
    cities: [
      { name: 'Itanagar', slug: 'itanagar', lat: 27.0844, lng: 93.6053 },
      { name: 'Tawang', slug: 'tawang', lat: 27.5860, lng: 91.8620 },
      { name: 'Ziro', slug: 'ziro', lat: 27.6300, lng: 93.8400 },
      { name: 'Bomdila', slug: 'bomdila', lat: 27.2700, lng: 92.4200 },
      { name: 'Dirang', slug: 'dirang', lat: 27.2400, lng: 92.1800 },
    ],
  },
  {
    name: 'Manipur',
    slug: 'manipur',
    capital: 'Imphal',
    description: 'The Jewel of India — Loktak Lake with floating islands, Keibul Lamjao National Park and vibrant Meitei culture.',
    image: IMAGE_URLS[9],
    gallery: IMAGE_URLS.slice(8, 11),
    weather: { summer: '20–30°C (March–May)', winter: '5–20°C (November–February)', monsoon: 'Heavy (June–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Meitei, Hindi',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Manipur Tourism', metaDescription: 'Visit Loktak Lake and Keibul Lamjao', keywords: ['Manipur', 'Loktak', 'Imphal', 'Northeast'] },
    cities: [
      { name: 'Imphal', slug: 'imphal', lat: 24.8170, lng: 93.9368 },
      { name: 'Loktak', slug: 'loktak', lat: 24.5500, lng: 93.8000 },
      { name: 'Ukhrul', slug: 'ukhrul', lat: 25.0700, lng: 94.3700 },
      { name: 'Churachandpur', slug: 'churachandpur', lat: 24.3300, lng: 93.6800 },
      { name: 'Senapati', slug: 'senapati', lat: 25.2500, lng: 94.0200 },
    ],
  },
  {
    name: 'Mizoram',
    slug: 'mizoram',
    capital: 'Aizawl',
    description: 'The Land of Blue Mountains — verdant hills, vibrant Mizo culture, Vantawng Falls and Phawngpui Blue Mountain.',
    image: IMAGE_URLS[12],
    gallery: IMAGE_URLS.slice(11, 14),
    weather: { summer: '20–29°C (March–May)', winter: '7–22°C (November–February)', monsoon: 'Very heavy (June–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Mizo, English, Hindi',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Mizoram Tourism', metaDescription: 'Explore Aizawl, Vantawng Falls and Phawngpui', keywords: ['Mizoram', 'Aizawl', 'Vantawng', 'Northeast'] },
    cities: [
      { name: 'Aizawl', slug: 'aizawl', lat: 23.7271, lng: 92.7176 },
      { name: 'Lunglei', slug: 'lunglei', lat: 22.8833, lng: 92.7500 },
      { name: 'Champhai', slug: 'champhai', lat: 23.4500, lng: 93.3300 },
      { name: 'Serchhip', slug: 'serchhip', lat: 23.3300, lng: 92.8500 },
      { name: 'Kolasib', slug: 'kolasib', lat: 24.2200, lng: 92.6800 },
    ],
  },
  {
    name: 'Nagaland',
    slug: 'nagaland',
    capital: 'Kohima',
    description: "The Land of Festivals — Hornbill Festival showcases warrior tribes' traditions, hills, forests and unique Naga cuisine.",
    image: IMAGE_URLS[9],
    gallery: IMAGE_URLS.slice(8, 11),
    weather: { summer: '16–30°C (March–May)', winter: '4–20°C (November–February)', monsoon: 'Heavy (June–September)' },
    bestTimeToVisit: 'October to May',
    localLanguage: 'English, Nagamese',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Nagaland Tourism', metaDescription: 'Discover Hornbill Festival and Dzukou Valley', keywords: ['Nagaland', 'Hornbill', 'Kohima', 'Dzukou'] },
    cities: [
      { name: 'Kohima', slug: 'kohima', lat: 25.6751, lng: 94.1086 },
      { name: 'Dimapur', slug: 'dimapur', lat: 25.9000, lng: 93.7300 },
      { name: 'Mokokchung', slug: 'mokokchung', lat: 26.3300, lng: 94.5200 },
      { name: 'Wokha', slug: 'wokha', lat: 26.1100, lng: 94.2700 },
      { name: 'Mon', slug: 'mon', lat: 26.7300, lng: 94.7300 },
    ],
  },
  {
    name: 'Tripura',
    slug: 'tripura',
    capital: 'Agartala',
    description: 'A small state with rich heritage — Ujjayanta Palace, serene Neermahal Water Palace, Unakoti rock carvings and unique cultures.',
    image: IMAGE_URLS[19],
    gallery: IMAGE_URLS.slice(18, 21),
    weather: { summer: '28–36°C (March–June)', winter: '12–24°C (November–February)', monsoon: 'Heavy (June–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Bengali, Kokborok, Hindi',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Tripura Tourism', metaDescription: 'Visit Neermahal, Ujjayanta Palace and Unakoti', keywords: ['Tripura', 'Neermahal', 'Agartala', 'Unakoti'] },
    cities: [
      { name: 'Agartala', slug: 'agartala', lat: 23.8315, lng: 91.2868 },
      { name: 'Udaipur', slug: 'udaipur-tripura', lat: 23.5300, lng: 91.4800 },
      { name: 'Dharmanagar', slug: 'dharmanagar', lat: 24.3700, lng: 92.1700 },
      { name: 'Kailashahar', slug: 'kailashahar', lat: 24.3300, lng: 92.0000 },
      { name: 'Ambassa', slug: 'ambassa', lat: 23.9300, lng: 91.8500 },
    ],
  },
  {
    name: 'Jharkhand',
    slug: 'jharkhand',
    capital: 'Ranchi',
    description: 'The land of forests and waterfalls — tribal heartland, Hundru Falls, Betla National Park, Parasnath Jain hills and Jamshedpur.',
    image: IMAGE_URLS[27],
    gallery: IMAGE_URLS.slice(26, 28),
    weather: { summer: '30–42°C (April–June)', winter: '8–22°C (November–February)', monsoon: 'Heavy (July–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Hindi, Santali, Bengali',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Jharkhand Tourism', metaDescription: 'Explore Hundru Falls, Betla and Parasnath', keywords: ['Jharkhand', 'Ranchi', 'Hundru', 'Betla'] },
    cities: [
      { name: 'Ranchi', slug: 'ranchi', lat: 23.3441, lng: 85.3096 },
      { name: 'Jamshedpur', slug: 'jamshedpur', lat: 22.8046, lng: 86.2029 },
      { name: 'Dhanbad', slug: 'dhanbad', lat: 23.7957, lng: 86.4304 },
      { name: 'Hazaribagh', slug: 'hazaribagh', lat: 23.9900, lng: 85.3600 },
      { name: 'Deoghar', slug: 'deoghar', lat: 24.4900, lng: 86.7000 },
    ],
  },
  {
    name: 'Chhattisgarh',
    slug: 'chhattisgarh',
    capital: 'Raipur',
    description: 'The rice bowl of central India — ancient temples, magnificent Chitrakote Falls, rich tribal culture and dense sal forests.',
    image: IMAGE_URLS[9],
    gallery: IMAGE_URLS.slice(8, 11),
    weather: { summer: '35–44°C (April–June)', winter: '10–28°C (November–February)', monsoon: 'Moderate (July–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Hindi, Chhattisgarhi',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Chhattisgarh Tourism', metaDescription: 'Visit Chitrakote Falls, Bastar and Sirpur', keywords: ['Chhattisgarh', 'Chitrakote', 'Bastar', 'Raipur'] },
    cities: [
      { name: 'Raipur', slug: 'raipur', lat: 21.2514, lng: 81.6296 },
      { name: 'Bastar', slug: 'bastar', lat: 19.1000, lng: 81.9000 },
      { name: 'Bilaspur', slug: 'bilaspur', lat: 22.0797, lng: 82.1409 },
      { name: 'Jagdalpur', slug: 'jagdalpur', lat: 19.0800, lng: 82.0300 },
      { name: 'Kanker', slug: 'kanker', lat: 20.2700, lng: 81.4900 },
    ],
  },
  {
    name: 'Haryana',
    slug: 'haryana',
    capital: 'Chandigarh',
    description: 'The land of the Bhagavad Gita — Kurukshetra battlefield, industrial Gurugram, Sultanpur Bird Sanctuary and agricultural heritage.',
    image: IMAGE_URLS[0],
    gallery: IMAGE_URLS.slice(0, 3),
    weather: { summer: '35–45°C (April–June)', winter: '2–18°C (December–February)', monsoon: 'Moderate (July–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Hindi, Haryanvi',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Haryana Tourism', metaDescription: 'Explore Kurukshetra, Sultanpur and Pinjore', keywords: ['Haryana', 'Kurukshetra', 'Sultanpur', 'Gurugram'] },
    cities: [
      { name: 'Gurugram', slug: 'gurugram', lat: 28.4595, lng: 77.0266 },
      { name: 'Kurukshetra', slug: 'kurukshetra', lat: 29.9677, lng: 76.8774 },
      { name: 'Faridabad', slug: 'faridabad', lat: 28.4089, lng: 77.3178 },
      { name: 'Panipat', slug: 'panipat', lat: 29.3909, lng: 76.9635 },
      { name: 'Karnal', slug: 'karnal', lat: 29.6857, lng: 76.9905 },
    ],
  },
  {
    name: 'Telangana',
    slug: 'telangana',
    capital: 'Hyderabad',
    description: "Home to Hyderabad's Charminar and world-famous biryani — Nizam heritage meets modern IT hubs and ancient Warangal forts.",
    image: IMAGE_URLS[27],
    gallery: IMAGE_URLS.slice(26, 28),
    weather: { summer: '32–42°C (March–June)', winter: '15–28°C (November–February)', monsoon: 'Moderate (July–September)' },
    bestTimeToVisit: 'October to March',
    localLanguage: 'Telugu, Urdu, Hindi',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    seo: { title: 'Telangana Tourism', metaDescription: 'Visit Charminar, Golconda Fort and Warangal', keywords: ['Telangana', 'Hyderabad', 'Charminar', 'Golconda'] },
    cities: [
      { name: 'Hyderabad', slug: 'hyderabad', lat: 17.3850, lng: 78.4867 },
      { name: 'Warangal', slug: 'warangal', lat: 17.9689, lng: 79.5941 },
      { name: 'Nizamabad', slug: 'nizamabad', lat: 18.6725, lng: 78.0941 },
      { name: 'Karimnagar', slug: 'karimnagar', lat: 18.4386, lng: 79.1288 },
      { name: 'Ramagundam', slug: 'ramagundam', lat: 18.7550, lng: 79.4650 },
    ],
  },
];

// Helper to generate places for a city
function generatePlacesForCity(city: any, stateSlug: string, index: number) {
  const placeNames = [
    `${city.name} Fort`, `${city.name} Palace`, `${city.name} Temple`,
    `${city.name} Lake`, `${city.name} Garden`, `${city.name} Museum`,
    `${city.name} Market`, `${city.name} Hill`, `${city.name} Beach`,
    `${city.name} Wildlife Sanctuary`,
  ];
  const categories = ['Heritage', 'Religious', 'Hill Station', 'Beach', 'Wildlife', 'Adventure', 'Family Trip', 'Honeymoon'];

  return placeNames.map((name, i) => ({
    name: name,
    slug: `${city.slug}-${name.toLowerCase().replace(/\s+/g, '-')}`,
    stateSlug,
    citySlug: city.slug,
    description: `Explore the magnificent ${name}, one of the most popular attractions in ${city.name}. This stunning destination offers breathtaking views, rich history, and unforgettable experiences for visitors from around the world.`,
    location: { latitude: city.lat + (Math.random() - 0.5) * 0.1, longitude: city.lng + (Math.random() - 0.5) * 0.1 },
    category: [categories[Math.floor(Math.random() * categories.length)]],
    bestTimeToVisit: 'October to March',
    openingTime: '6:00 AM',
    closingTime: '6:00 PM',
    entryFee: ['Free', '₹20', '50', '₹100', '₹200'][Math.floor(Math.random() * 5)],
    images: [IMAGE_URLS[(index * 10 + i) % IMAGE_URLS.length]],
    history: `The ${name} has a rich history dating back centuries. It has been a center of culture, trade, and spirituality, attracting visitors from all over the world.`,
    highlights: ['Stunning Architecture', 'Beautiful Views', 'Rich History', 'Photography Spot', 'Cultural Experience'],
    thingsToKnow: ['Carry water bottles', 'Wear comfortable shoes', 'Respect local customs', 'No photography inside temple areas'],
    photography: true,
    weather: { summer: 'Hot, 30-40°C', winter: 'Pleasant, 10-25°C', monsoon: 'Moderate rainfall' },
    safetyTips: ['Stay hydrated', 'Keep valuables safe', 'Follow guide instructions', 'Respect wildlife'],
    transportation: {
      byFlight: { nearestAirport: `${city.name} Airport`, distance: '15 km', cabCost: '₹300-500' },
      byTrain: { nearestStation: `${city.name} Junction`, distance: '5 km', taxiFare: '₹100-200' },
      byBus: { busStand: `${city.name} Bus Stand`, autoFare: '₹30-60' },
      privateCab: '₹1500/day',
      bikeRental: '₹500/day',
    },
    estimatedCost: {
      budget: { hotel: '₹800', food: '₹400', travel: '₹300', tickets: '₹200', shopping: '₹500', total: '₹2,200' },
      standard: { hotel: '₹2,500', food: '₹800', travel: '₹600', tickets: '₹500', shopping: '₹1,000', total: '5,400' },
      luxury: { hotel: '₹8,000', food: '₹2,000', travel: '₹1,500', tickets: '₹1,000', shopping: '₹3,000', total: '₹15,500' },
    },
    bestMonths: [
      { month: 'October', temperature: '20-28°C', crowd: 'Moderate', recommendation: 'Great weather' },
      { month: 'November', temperature: '15-25°C', crowd: 'High', recommendation: 'Best time' },
      { month: 'December', temperature: '10-22°C', crowd: 'High', recommendation: 'Peak season' },
    ],
    localFoods: ['Local Thali', 'Street Food', 'Traditional Sweets', 'Regional Speciality'],
    travelTips: {
      dos: ['Book tickets online', 'Visit early morning', 'Hire a local guide', 'Try local food'],
      donts: ['Dont litter', 'Dont touch artifacts', 'Dont feed animals', 'Dont skip sunscreen'],
      safety: ['Carry ID proof', 'Keep emergency contacts', 'Stay on marked paths', 'Drink bottled water'],
    },
    localLanguage: 'Hindi, English',
    emergencyNumbers: { police: '100', ambulance: '108', fire: '101' },
    faqs: [
      { question: 'What is the best time to visit?', answer: 'October to March is the best time with pleasant weather.' },
      { question: 'How much time is needed?', answer: 'Plan for 2-3 hours to explore properly.' },
      { question: 'Is parking available?', answer: 'Yes, paid parking is available near the entrance.' },
    ],
    rating: 4.0 + Math.random() * 1,
    published: true,
    seo: {
      title: `${name} - ${city.name} Tourism`,
      metaDescription: `Visit ${name} in ${city.name} - one of the top attractions`,
      keywords: [name, city.name, stateSlug, 'tourism', 'travel'],
    },
    _hotelSlugs: [],
    _restaurantSlugs: [],
  }));
}

// Helper to generate hotels for a city
function generateHotelsForCity(city: any, index: number) {
  const hotelNames = [
    `${city.name} Grand Hotel`, `${city.name} Palace Resort`, `${city.name} Heritage Inn`,
    `${city.name} Luxury Suites`, `${city.name} Budget Stay`,
  ];

  return hotelNames.map((name, i) => ({
    name: name,
    slug: `${city.slug}-${name.toLowerCase().replace(/\s+/g, '-')}`,
    description: `Experience comfort and hospitality at ${name}, located in the heart of ${city.name}. Offering modern amenities with traditional charm, this hotel is perfect for both leisure and business travelers.`,
    address: `${100 + i * 50} Main Road, ${city.name}`,
    location: { latitude: city.lat + (Math.random() - 0.5) * 0.05, longitude: city.lng + (Math.random() - 0.5) * 0.05 },
    googleMapLink: `https://maps.google.com/?q=${city.lat},${city.lng}`,
    phone: `+91 ${90000 + i * 1000}00000`,
    website: `https://www.${name.toLowerCase().replace(/\s+/g, '')}.com`,
    starRating: 3 + Math.floor(Math.random() * 3),
    pricePerNight: [800, 1500, 2500, 4000, 8000][i],
    amenities: AMENITIES.slice(0, 4 + Math.floor(Math.random() * 4)),
    images: [HOTEL_IMAGES[i % HOTEL_IMAGES.length]],
    distance: `${0.5 + i * 0.5} km from city center`,
    category: ['Luxury', 'Budget', 'Heritage', 'Business', 'Resort'][i] ? ['Luxury', 'Budget', 'Heritage', 'Business', 'Resort'][i] : 'Budget',
    published: true,
  }));
}

// Helper to generate restaurants for a city
function generateRestaurantsForCity(city: any, index: number) {
  const restaurantNames = [
    `${city.name} Kitchen`, `${city.name} Spice House`, `${city.name} Food Court`,
    `${city.name} Dhaba`, `${city.name} Fine Dining`,
  ];

  return restaurantNames.map((name, i) => ({
    name: name,
    slug: `${city.slug}-${name.toLowerCase().replace(/\s+/g, '-')}`,
    description: `Savor authentic flavors at ${name}, a popular dining destination in ${city.name}. Known for its delicious cuisine, warm ambiance, and excellent service.`,
    cuisine: [CUISINES[Math.floor(Math.random() * CUISINES.length)], CUISINES[Math.floor(Math.random() * CUISINES.length)]],
    address: `${200 + i * 100} Food Street, ${city.name}`,
    location: { latitude: city.lat + (Math.random() - 0.5) * 0.05, longitude: city.lng + (Math.random() - 0.5) * 0.05 },
    googleMapLink: `https://maps.google.com/?q=${city.lat},${city.lng}`,
    phone: `+91 ${91000 + i * 1000}00000`,
    website: `https://www.${name.toLowerCase().replace(/\s+/g, '')}.com`,
    averageCost: [300, 500, 800, 1200, 2000][i],
    openingTime: ['10:00 AM', '11:00 AM', '12:00 PM', '7:00 AM', '11:30 AM'][i],
    closingTime: ['10:00 PM', '11:00 PM', '10:30 PM', '9:00 PM', '11:30 PM'][i],
    images: [RESTAURANT_IMAGES[i % RESTAURANT_IMAGES.length]],
    vegNonVeg: ['veg', 'non-veg', 'both', 'veg', 'both'][i] as 'veg' | 'non-veg' | 'both',
    rating: 3.5 + Math.random() * 1.5,
    distance: `${0.3 + i * 0.3} km from city center`,
    published: true,
  }));
}

export function generateAllSeedData() {
  const allStates: any[] = [];
  const allCities: any[] = [];
  const allPlaces: any[] = [];
  const allHotels: any[] = [];
  const allRestaurants: any[] = [];

  STATES_DATA.forEach((stateData, stateIndex) => {
    const stateSlug = stateData.slug;

    // Add state
    allStates.push({
      name: stateData.name,
      slug: stateData.slug,
      description: stateData.description,
      capital: stateData.capital,
      image: stateData.image,
      gallery: stateData.gallery,
      weather: stateData.weather,
      bestTimeToVisit: stateData.bestTimeToVisit,
      localLanguage: stateData.localLanguage,
      emergencyNumbers: stateData.emergencyNumbers,
      published: true,
      seo: stateData.seo,
      _popularCitySlugs: stateData.cities.map(c => c.slug),
      _popularPlaceSlugs: [],
    });

    // Generate cities, places, hotels, restaurants for each city
    stateData.cities.forEach((city: any, cityIndex) => {
      const citySlug = city.slug;

      // Add city
      allCities.push({
        name: city.name,
        slug: citySlug,
        stateSlug,
        description: `${city.name} is a vibrant city in ${stateData.name}, known for its rich culture, beautiful landscapes, and warm hospitality. A must-visit destination for travelers exploring ${stateData.name}.`,
        image: IMAGE_URLS[(stateIndex * 5 + cityIndex) % IMAGE_URLS.length],
        gallery: IMAGE_URLS.slice((stateIndex * 5 + cityIndex) % IMAGE_URLS.length, ((stateIndex * 5 + cityIndex) % IMAGE_URLS.length) + 3),
        location: { latitude: city.lat, longitude: city.lng },
        weather: stateData.weather,
        bestTimeToVisit: stateData.bestTimeToVisit,
        transportation: {
          nearestAirport: { name: `${city.name} Airport`, distance: '15 km', cabCost: '₹300-500' },
          nearestStation: { name: `${city.name} Junction`, distance: '5 km', taxiFare: '₹100-200' },
          busStand: { name: `${city.name} Bus Stand`, autoFare: '30-60' },
        },
        estimatedBudget: {
          budget: { hotel: '₹800', food: '₹400', travel: '₹300', tickets: '₹200', shopping: '₹500', total: '₹2,200' },
          standard: { hotel: '₹2,500', food: '₹800', travel: '600', tickets: '₹500', shopping: '₹1,000', total: '₹5,400' },
          luxury: { hotel: '8,000', food: '₹2,000', travel: '₹1,500', tickets: '₹1,000', shopping: '₹3,000', total: '₹15,500' },
        },
        localFoods: ['Local Thali', 'Street Food', 'Traditional Sweets', 'Regional Speciality', 'Famous Snack'],
        travelTips: {
          dos: ['Book in advance', 'Try local food', 'Visit early morning', 'Hire local guide'],
          donts: ['Dont litter', 'Dont skip sunscreen', 'Dont ignore local customs', 'Dont travel late night'],
          safety: ['Carry ID', 'Keep emergency contacts', 'Use registered taxis', 'Drink bottled water'],
        },
        published: true,
        seo: {
          title: `${city.name} Tourism - ${stateData.name}`,
          metaDescription: `Explore ${city.name} in ${stateData.name} - top attractions, hotels and restaurants`,
          keywords: [city.name, stateData.name, 'tourism', 'travel', 'hotels'],
        },
        _hotelSlugs: [],
        _restaurantSlugs: [],
        _popularPlaceSlugs: [],
      });

      // Generate 10 places for this city
      const cityPlaces = generatePlacesForCity(city, stateSlug, stateIndex * 5 + cityIndex);
      cityPlaces.forEach((place, placeIndex) => {
        allPlaces.push(place);
        allCities[allCities.length - 1]._popularPlaceSlugs.push(place.slug);
      });

      // Generate 5 hotels for this city
      const cityHotels = generateHotelsForCity(city, stateIndex * 5 + cityIndex);
      cityHotels.forEach((hotel) => {
        allHotels.push(hotel);
        allCities[allCities.length - 1]._hotelSlugs.push(hotel.slug);
      });

      // Generate 5 restaurants for this city
      const cityRestaurants = generateRestaurantsForCity(city, stateIndex * 5 + cityIndex);
      cityRestaurants.forEach((restaurant) => {
        allRestaurants.push(restaurant);
        allCities[allCities.length - 1]._restaurantSlugs.push(restaurant.slug);
      });

      // Update state's popular places
      allStates[allStates.length - 1]._popularPlaceSlugs.push(...cityPlaces.slice(0, 2).map(p => p.slug));
    });
  });

  return {
    statesData: allStates,
    citiesData: allCities,
    placesData: allPlaces,
    hotelsData: allHotels,
    restaurantsData: allRestaurants,
  };
}
